/*
 * JanelaPrincipal.java
 *
 * Created on 19 de Abril de 2006, 23:29
 */

package petrinet10.gui.visualizacao;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.net.InetAddress;
import java.net.UnknownHostException;
import javax.swing.ButtonGroup;
import javax.swing.JDesktopPane;
import petrinet10.gui.controle.Controle;
import remoto.JanelaRemoto;
import webservice.Conecta;
import webservice.Token;

/**
 *
 * @author  _Renatu
 */
public class JanelaPrincipal extends javax.swing.JFrame {
    
    //public Conecta Servidor;
     
        //TESTE
    //Conecta Servidor = new Conecta();
    
    /** Creates new form JanelaPrincipal */
    public JanelaPrincipal() {
        initComponents();
        ButtonGroup bg = new ButtonGroup();
        bg.add(jToggleButton1);
        bg.add(jToggleButton2);
        bg.add(jToggleButton3);
        bg.add(jToggleButton4);
        bg.add(jToggleButton5);
        bg.add(jToggleButton6);
        bg.add(jToggleButton7);
        ModeloTabelaPropriedades mtp = new ModeloTabelaPropriedades();
        jTable1.setModel(mtp);
        jTable1.setDefaultRenderer(Color.class, new RenderizadorDeCor());
        jTable1.setDefaultEditor(Color.class, new EditorDeCor());
        Controle.getControle().setModeloTabelaPropriedades(mtp);
        ModeloTabelaGerenciador mtg = new ModeloTabelaGerenciador(jTable2);
        jTable2.setModel(mtg);
        jTable2.setDefaultRenderer(Class.class, new RenderizadorGerenciador());
        jTable2.getSelectionModel().addListSelectionListener(mtg);
        Controle.getControle().setModeloGerenciador(mtg);
        Controle.getControle().setTabelaGerenciador(jTable2);
        jToolBar3.setVisible(false);
            
        //isso é necessário para retirar a toolbar.
        repaint();
       
    }
            
    public JDesktopPane getJDesktopPane() {
        return this.jDesktopPane1;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Código Gerado ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel2 = new javax.swing.JPanel();
        jToolBar2 = new javax.swing.JToolBar();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        jToggleButton7 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jToggleButton5 = new javax.swing.JToggleButton();
        jToggleButton6 = new javax.swing.JToggleButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jSplitPane2 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new JTabela();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jToolBar3 = new javax.swing.JToolBar();
        jLabel10 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Petri Net 2.0 - Implementa\u00e7\u00e3o de M\u00f3dulo de Fus\u00e3o de Transi\u00e7\u00f5es");
        setBounds(new java.awt.Rectangle(0, 0, 1024, 768));
        setMinimumSize(new java.awt.Dimension(824, 240));
        jSplitPane1.setDividerLocation(200);
        jPanel2.setLayout(new java.awt.BorderLayout());

        jToolBar2.setFloatable(false);
        jToolBar2.setOrientation(1);
        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/petrinet10/imagens/Seta.png")));
        jToggleButton1.setSelected(true);
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jToolBar2.add(jToggleButton1);

        jToggleButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/petrinet10/imagens/reta.gif")));
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        jToolBar2.add(jToggleButton2);

        jToggleButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/petrinet10/imagens/retangulo.gif")));
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });

        jToolBar2.add(jToggleButton3);

        jToggleButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/petrinet10/imagens/elipse.gif")));
        jToggleButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton4ActionPerformed(evt);
            }
        });

        jToolBar2.add(jToggleButton4);

        jToggleButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/petrinet10/imagens/texto.gif")));
        jToggleButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton7ActionPerformed(evt);
            }
        });

        jToolBar2.add(jToggleButton7);

        jLabel1.setText("  ");
        jToolBar2.add(jLabel1);

        jToggleButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/petrinet10/imagens/lugar.png")));
        jToggleButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton5ActionPerformed(evt);
            }
        });

        jToolBar2.add(jToggleButton5);

        jToggleButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/petrinet10/imagens/transicao.png")));
        jToggleButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton6ActionPerformed(evt);
            }
        });

        jToolBar2.add(jToggleButton6);

        jPanel2.add(jToolBar2, java.awt.BorderLayout.WEST);

        jDesktopPane1.setBackground(new java.awt.Color(102, 102, 102));
        jDesktopPane1.setEnabled(false);
        jDesktopPane1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                jDesktopPane1ComponentMoved(evt);
            }
        });
        jDesktopPane1.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jDesktopPane1ComponentAdded(evt);
            }
        });
        jDesktopPane1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDesktopPane1PropertyChange(evt);
            }
        });

        jPanel2.add(jDesktopPane1, java.awt.BorderLayout.CENTER);

        jSplitPane1.setRightComponent(jPanel2);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jSplitPane2.setDividerLocation(150);
        jSplitPane2.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jScrollPane1.setMinimumSize(new java.awt.Dimension(100, 100));
        jScrollPane1.setOpaque(false);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Propriedade", "Valor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jSplitPane2.setTopComponent(jScrollPane1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Elemento", "Tipo"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jSplitPane2.setBottomComponent(jScrollPane2);

        jPanel1.add(jSplitPane2, java.awt.BorderLayout.CENTER);

        jSplitPane1.setLeftComponent(jPanel1);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        jToolBar1.setFloatable(false);
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/petrinet10/imagens/Novo.png")));
        jButton1.setToolTipText("Novo");
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jToolBar1.add(jButton1);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/petrinet10/imagens/Abrir.png")));
        jButton2.setToolTipText("Abrir");
        jButton2.setBorderPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jToolBar1.add(jButton2);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/petrinet10/imagens/Salvar.png")));
        jButton3.setToolTipText("Salvar");
        jButton3.setBorderPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jToolBar1.add(jButton3);

        jLabel2.setText("           ");
        jToolBar1.add(jLabel2);

        jButton7.setText("Ligar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jToolBar1.add(jButton7);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/petrinet10/imagens/play.png")));
        jButton4.setToolTipText("Rodar");
        jButton4.setBorderPainted(false);
        jButton4.setEnabled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jToolBar1.add(jButton4);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/petrinet10/imagens/stop.png")));
        jButton5.setToolTipText("Parar");
        jButton5.setBorderPainted(false);
        jButton5.setEnabled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jToolBar1.add(jButton5);

        jButton9.setText("Reset");
        jButton9.setEnabled(false);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jToolBar1.add(jButton9);

        jButton8.setText("Passo");
        jButton8.setEnabled(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jToolBar1.add(jButton8);

        jButton11.setText("Auto");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jToolBar1.add(jButton11);

        jLabel3.setText("           ");
        jToolBar1.add(jLabel3);

        jButton6.setText("Vari\u00e1veis");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jToolBar1.add(jButton6);

        jLabel4.setText("   ");
        jToolBar1.add(jLabel4);

        jButton10.setText("Iniciar Servidor");
        jButton10.setEnabled(false);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jToolBar1.add(jButton10);

        jLabel6.setText("  ");
        jToolBar1.add(jLabel6);

        jToolBar3.setMaximumSize(new java.awt.Dimension(300, 26));
        jToolBar3.setMinimumSize(new java.awt.Dimension(300, 26));
        jLabel10.setText(" Est: ");
        jLabel10.setEnabled(false);
        jToolBar3.add(jLabel10);

        jTextField4.setToolTipText("Nome desta Estacao");
        jTextField4.setEnabled(false);
        jTextField4.setMaximumSize(new java.awt.Dimension(20, 20));
        jTextField4.setMinimumSize(new java.awt.Dimension(20, 20));
        jToolBar3.add(jTextField4);

        jLabel7.setText(" porta: ");
        jLabel7.setEnabled(false);
        jToolBar3.add(jLabel7);

        jTextField1.setToolTipText("Porta na qual sera iniciado o servidor local");
        jTextField1.setEnabled(false);
        jTextField1.setMaximumSize(new java.awt.Dimension(50, 20));
        jTextField1.setMinimumSize(new java.awt.Dimension(50, 20));
        jToolBar3.add(jTextField1);

        jLabel8.setText(" IP ");
        jLabel8.setEnabled(false);
        jToolBar3.add(jLabel8);

        jTextField2.setToolTipText("IP da proxima estacao");
        jTextField2.setEnabled(false);
        jTextField2.setMaximumSize(new java.awt.Dimension(95, 20));
        jTextField2.setMinimumSize(new java.awt.Dimension(95, 20));
        jToolBar3.add(jTextField2);

        jLabel9.setText(" : ");
        jLabel9.setEnabled(false);
        jToolBar3.add(jLabel9);

        jTextField3.setToolTipText("Porta do servidor da proxima estacao");
        jTextField3.setEnabled(false);
        jTextField3.setMaximumSize(new java.awt.Dimension(50, 20));
        jTextField3.setMinimumSize(new java.awt.Dimension(50, 20));
        jToolBar3.add(jTextField3);

        jToolBar1.add(jToolBar3);

        jToolBar1.add(jLabel5);

        jPanel3.setMaximumSize(new java.awt.Dimension(280, 60));
        jPanel3.setPreferredSize(new java.awt.Dimension(140, 24));
        jLabel11.setText("Tempo");
        jLabel11.setMaximumSize(new java.awt.Dimension(240, 14));
        jLabel11.setPreferredSize(new java.awt.Dimension(150, 14));
        jPanel3.add(jLabel11);

        jToolBar1.add(jPanel3);

        getContentPane().add(jToolBar1, java.awt.BorderLayout.NORTH);

        jMenu1.setText("Arquivo");
        jMenuItem1.setMnemonic('S');
        jMenuItem1.setText("Sair");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });

        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("AcessoRemoto");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });

        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
// TODO adicione seu código de manipulação aqui:
        //esse botão servirá de teste para separar envios e recebimentos do "close server"
        //Conecta.getServidor().teste();
        //Controle.getControle().auto();
        
        //E SE EU FIZER--> While Token.getStatus...!=parar-->
        jLabel11.setText(" TempoLocal = "+Token.getToken().getRelogioLocal());
        repaint();
        jPanel3.paintImmediately(0,0,1024,768);
        //this.jToolBar3.paintImmediately(0,0,1024,768);       
        
        Controle.getControle().auto(); //naum sei o que ocorre... mas isso naum funciona
        //experimente colocar uns println pra saber aonde entra ou não...
        

        
//        while (Token.getToken().getInstrucao()==0) {
//            Controle.getControle().passo();
//        }
            
        
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
// TODO add your handling code here:
        JanelaRemoto jr = new JanelaRemoto();
        jr.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed
    
    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
// TODO add your handling code here:
        String texto = jButton10.getText();
        
        if (texto.equals("Iniciar Servidor")) {
            jButton10.setText("Finalizar Servidor");
            jToolBar3.setVisible(false);
            
            //isso é necessário para retirar a toolbar.
            repaint();
            
           
            
            //iniciado o servidor (station Name, port, IP, port2)
            if (jTextField4.getText().equals("A")) {
                Conecta.getServidor().iniciaA(jTextField4.getText().charAt(0), Integer.parseInt(jTextField1.getText()),
                        jTextField2.getText(), Integer.parseInt(jTextField3.getText()));
                
            } else {
                
                /*Servidor*/
                Conecta.getServidor().inicia(jTextField4.getText().charAt(0), 
                        Integer.parseInt(jTextField1.getText()),
                        jTextField2.getText(), Integer.parseInt(jTextField3.getText()));
                /*Servidor*/
                //Conecta.getServidor().envia("B4321");
            }
                        
            byte[] ipAddr = null;
            String hostname = "";
            try {
                InetAddress addr = InetAddress.getLocalHost();
                // Get IP Address
                ipAddr = addr.getAddress();
                // Get hostname
                hostname = addr.getHostName();
            } catch (UnknownHostException e) {
                
            }
            String ipAddrStr = "";
            for (int i=0; i<ipAddr.length; i++) {
                if (i > 0) {
                    ipAddrStr += ".";
                }
                ipAddrStr += ipAddr[i]&0xFF;
            }
            
            //jLabel5.setText("Servidor rodando em: " + hostname + " - " + ipAddrStr);
//            jLabel5.setText("Estacao "+Servidor.stationName+ " em "
//                    +ipAddrStr+":"+Servidor.port+". Conectada a "+Servidor.computer+":"
//                    +Servidor.port2);
            
            
            //WORKING FINE
            //System.out.println("Station: "+Conecta.getServidor().stationName);
            //System.out.println("Station: "+Conecta.servidor.stationName);
            //System.out.println("Station: "+jTextField4.getText().charAt(0));
            
            jLabel5.setText("Estacao "+Conecta.getServidor().stationName+ " em "
                    +ipAddrStr+":"+Conecta.getServidor().port+". Conectada a "+Conecta.getServidor().computer+":"
                    +Conecta.getServidor().port2);
//            jLabel5.setText("Working");
            jLabel5.setVisible(true);
            repaint();
            
            //AGORA VOU FAZER  O "CONTROLE DO TOKEN - ESPERA DE MENSAGEM"
            Token.getToken().ControleToken();
            
        } else {
            //Conecta.getServidor().teste();
//            jLabel5.setText("A finalizar Estacao "+Conecta.getServidor().stationName+"...");
//            jLabel5.setVisible(true);
//            repaint();
             
            Conecta.getServidor().desligaConexoes();
                       
            jLabel5.setText("");
            jLabel5.setVisible(true);
            jButton10.setText("Iniciar Servidor");
            
            jToolBar3.setVisible(true); //recolocando a toolbar
            
            repaint();
            
            //Conecta.getServidor().desligaConexoes();
                       
                
        }
    }//GEN-LAST:event_jButton10ActionPerformed
    
    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
// TODO add your handling code here:
        Controle.getControle().reset();
    }//GEN-LAST:event_jButton9ActionPerformed
    
    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
// TODO add your handling code here:
        Controle.getControle().passo();
        jLabel11.setText(" TempoLocal = "+Token.getToken().getRelogioLocal());
        repaint();
    }//GEN-LAST:event_jButton8ActionPerformed
    
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
// TODO add your handling code here:
        if (jButton7.getText().equals("Ligar")) {
            jButton7.setText("Desligar");
            jToolBar2.setVisible(false);
            jToggleButton1.setSelected(true);
            Controle.getControle().setFuncao(Controle.SETA);
            jButton4.setEnabled(false);//mudei para false
            jButton5.setEnabled(false);//mudei para false
            jButton4.setVisible(false);
            jButton5.setVisible(false);
            
            jButton8.setEnabled(true);
            jButton6.setEnabled(false);
            jButton6.setVisible(false);//tirei...
            
            jButton9.setEnabled(false);//mudei para false
            jButton9.setVisible(false);
            
            jButton10.setEnabled(true);
            
            //fazendo aparecer campos IP:port do TOken Ring ao Clicar "Ligar"
            jLabel7.setEnabled(true);
            jLabel8.setEnabled(true);
            jLabel9.setEnabled(true);
            jLabel10.setEnabled(true);
            jTextField1.setEnabled(true);
            jTextField2.setEnabled(true);
            jTextField3.setEnabled(true);
            jTextField4.setEnabled(true);
            
            jToolBar3.setVisible(true);
            
            //isso é necessário para retirar a toolbar.
            repaint();
            
            jPanel2.add(Controle.getControle().getPainelIO(), "East");
            Controle.getControle().ligar();
        } else {
            jButton7.setText("Ligar");
            jToolBar2.setVisible(true);
            jButton4.setEnabled(false);
            jButton5.setEnabled(false);
            jButton8.setEnabled(false);
            jButton6.setEnabled(true);
            jButton9.setEnabled(false);
            jButton10.setEnabled(false);
            jToolBar3.setVisible(false); //retirando a toolbar
            repaint();
            if (jButton10.getText().equals("Finalizar Servidor")) {
                jButton10.doClick();
                jButton10ActionPerformed(new ActionEvent(jButton10, 10, "Botao"));
            }
            Controle.getControle().desligar();
            jPanel2.remove(Controle.getControle().getPainelIO());
        }
    }//GEN-LAST:event_jButton7ActionPerformed
    
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
// TODO add your handling code here:
        new JanelaVariaveis(this, true).setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
// TODO add your handling code here:
        Controle.getControle().salvar();
    }//GEN-LAST:event_jButton3ActionPerformed
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here:
        Controle.getControle().abrir();
    }//GEN-LAST:event_jButton2ActionPerformed
    
    private void jDesktopPane1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDesktopPane1PropertyChange
// TODO add your handling code here:
    }//GEN-LAST:event_jDesktopPane1PropertyChange
    
    private void jDesktopPane1ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jDesktopPane1ComponentAdded
// TODO add your handling code here:
    }//GEN-LAST:event_jDesktopPane1ComponentAdded
    
    private void jDesktopPane1ComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jDesktopPane1ComponentMoved
// TODO add your handling code here:
    }//GEN-LAST:event_jDesktopPane1ComponentMoved
    
    public void repintarTabela() {
        jTable1.repaint();
    }
    
    private void jToggleButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton7ActionPerformed
// TODO add your handling code here:
        if (jToggleButton7.isSelected()) Controle.getControle().setFuncao(Controle.TEXTO);
        if (!jToggleButton1.isSelected()) Controle.getControle().limparSelecoes();
    }//GEN-LAST:event_jToggleButton7ActionPerformed
    
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
// TODO add your handling code here:
        Controle.getControle().parar();
    }//GEN-LAST:event_jButton5ActionPerformed
    
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
// TODO add your handling code here:
        Controle.getControle().rodar();
    }//GEN-LAST:event_jButton4ActionPerformed
    
    private void jToggleButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton6ActionPerformed
// TODO add your handling code here:
        if (jToggleButton6.isSelected()) Controle.getControle().setFuncao(Controle.TRANSICAO);
        if (!jToggleButton1.isSelected()) Controle.getControle().limparSelecoes();
    }//GEN-LAST:event_jToggleButton6ActionPerformed
    
    private void jToggleButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton5ActionPerformed
// TODO add your handling code here:
        if (jToggleButton5.isSelected()) Controle.getControle().setFuncao(Controle.LUGAR);
        if (!jToggleButton1.isSelected()) Controle.getControle().limparSelecoes();
    }//GEN-LAST:event_jToggleButton5ActionPerformed
    
    private void jToggleButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton4ActionPerformed
// TODO add your handling code here:
        if (jToggleButton4.isSelected()) Controle.getControle().setFuncao(Controle.ELIPSE);
        if (!jToggleButton1.isSelected()) Controle.getControle().limparSelecoes();
    }//GEN-LAST:event_jToggleButton4ActionPerformed
    
    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
// TODO add your handling code here:
        if (jToggleButton3.isSelected()) Controle.getControle().setFuncao(Controle.RETANGULO);
        if (!jToggleButton1.isSelected()) Controle.getControle().limparSelecoes();
    }//GEN-LAST:event_jToggleButton3ActionPerformed
    
    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
// TODO add your handling code here:
        if (jToggleButton2.isSelected()) Controle.getControle().setFuncao(Controle.RETA);
        if (!jToggleButton1.isSelected()) Controle.getControle().limparSelecoes();
    }//GEN-LAST:event_jToggleButton2ActionPerformed
    
    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
// TODO add your handling code here:
        if (jToggleButton1.isSelected()) Controle.getControle().setFuncao(Controle.SETA);
    }//GEN-LAST:event_jToggleButton1ActionPerformed
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
        Controle.getControle().criarNovaJanelaInterna("Novo");
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
// TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaPrincipal().setVisible(true);
            }
        });
    }
    
    // Declaração de variáveis - não modifique//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    public javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JToggleButton jToggleButton5;
    private javax.swing.JToggleButton jToggleButton6;
    private javax.swing.JToggleButton jToggleButton7;
    public javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JToolBar jToolBar3;
    // Fim da declaração de variáveis//GEN-END:variables
    
}
